### ISSUE TITLE
Resolutions Issue

### ISSUE THREAD

**Issue by itzdevilz97** [Trsak/esx_inventoryhud#17]
This may only work for 1920x1080 , people with lower resolution have issues  with some things on the interface hided

**Comment by itzdevilz97** [comment]
There is still the bug, people with 1366x768 monitor cant see all the inventory
http://prntscr.com/nj29ql

**Comment by Trsak** [comment]
Should be fixed with 3480138a0617cd8be68e6582fcc36817f130f77d
