### ISSUE TITLE
Is somethink wrong with my es_extended or...

### ISSUE THREAD

**Issue by Emilstag** [Trsak/esx_inventoryhud#2]
Help the none of the menu is opening.

[main.lua.pdf](https://github.com/Trsak/esx_inventoryhud/files/3076696/main.lua.pdf)

**Comment by theyellowguy** [comment]
Your PDF is unreadable.

**Comment by theyellowguy** [comment]
And show the errors, not the script.

**Comment by Trsak** [comment]
Please don't share your source code as PDF file. Did you resolve the issue?
