### ISSUE TITLE
players can add more than the set amount of item if they drag from vehicle inv over to main

### ISSUE THREAD

**Issue by wydox1SK** [Trsak/esx_inventoryhud#20]
Hey..

Having an issue where players can carry more than the set item max if they drag the item over from the vehicle inventory to the main.

For an example i have set max 40 cannabis to be able to be help, if a player has 40 on them, and 40 in the trunk he can simply drag the 40 from the truck over to his person and now carry 80 on him. This is very problematic.

**Comment by Trsak** [comment]
Then you are not using latest version of trunk.
