### ISSUE TITLE
Idea : Items which can close UI

### ISSUE THREAD

**Issue by Oldarorn** [Trsak/esx_inventoryhud#21]
Hi ! First, thanks for your amazing work, it's brilliant.

It's a simple idea I had, don't know if it's useful or not but it could be an enhancement if we could list some items in config.lua which will close the inventory when using.

For example, I'm going to fishing, when I'll use my fishing rod, it'll close the inventory.

**Comment by Trsak** [comment]
Added with 0884d253bb4fee2f603c6deb2d99902631eaa6d7
