### ISSUE TITLE
Unable to use items

### ISSUE THREAD

**Issue by VortexLife** [Trsak/esx_inventoryhud#22]
Unable to use custom items such as whisky beer, hamburgers and a few others items, is there a way to add custom items to the list so users can use the items?

**Comment by Trsak** [comment]
This is not inventory issue. If you can not use them, then you simply did not register them as usable in es extended.

**Comment by RagingNaClholic** [comment]
How did you fix this problem???

**Comment by loibuonbongtoi** [comment]
you up esx_status ??
