### ISSUE TITLE
Display player pod

### ISSUE THREAD

**Issue by dragonir44** [Trsak/esx_inventoryhud#25]
Hi i give an idea, it's possible to add the pod count of the player in the inventory?

**Comment by Trsak** [comment]
Not exactly sure what you mean?

**Comment by dragonir44** [comment]
Be able to see the weight remaining in the inventory, basically do as for your esx_inventoryhud_trunk 
(sorry for my bad english)

**Comment by Trsak** [comment]
This resource is just UI for es_extended inventory. To implement items and inventory weight, es_extended would have to be changed.
