### ISSUE TITLE
Can't give and drop some items

### ISSUE THREAD

**Issue by nviscomi** [Trsak/esx_inventoryhud#27]
Hi, i can't give and drop some items, i can give and drop only money and gun.

Can u please give me some information for reactivate the drop and give for the standard items like water etc?

**Comment by NebelRebell** [comment]
//LANGUAGE CAN BE CHANGED IN ui.html, SEARCH FOR <script src="locales/en.js"></script> AND CHANGE IT THERE

**Comment by Trsak** [comment]
Nothing to do with this resource. Your items are simply not set as droppable.
