### ISSUE TITLE
Bug - Searching players inventory

### ISSUE THREAD

**Issue by LowQualityPlays** [Trsak/esx_inventoryhud#32]
When we are searching another player inventory, we can drop the item, if the item is a weapon, it'll drop but the player being searched WONT LOSE IT. Making it easy to duping. Also, I can't get weapons from other players inventory into mine. It wont "refresh" when I drop them and it won't go into mine when i drag them.

Even when the gun appears to be dropped and there's nothing on the other player inventory, he can still get the weapon using the TAB wheel, so it appears that it's not refreshing the inventory for them.

Edit: Sometimes the gun doesn't even show on the other player's inventory.

Sorry if it's a little confuse. English is not my first language.

(I'm editing an issue, idk if it's against the rules, but my older issue was easily fixed and i think it was my fault).

**Comment by Ezi2k** [comment]
Got same issue, when i'm trying to search someones inventory weapons dose not appear until i've the weapon in my inventory.

**Comment by RoqueDEV** [comment]
https://github.com/Trsak/esx_inventoryhud/pull/53
