### ISSUE TITLE
No weapon in other player inventory

### ISSUE THREAD

**Issue by KingRyuShin** [Trsak/esx_inventoryhud#34]
I'm using the new update on esx_policejob.. when I open other player inventory I can see all of the item but not the weapon..

**Comment by dolutattoo** [comment]
Same problem,

I can see the target's weapons **ONLY** if I have them into my loadout too !

Please can someone help me to fix it ?

**Comment by KingRyuShin** [comment]
@Trsak Any news for that problem ?

**Comment by RoqueDEV** [comment]
https://github.com/Trsak/esx_inventoryhud/pull/53
