### ISSUE TITLE
What about society support

### ISSUE THREAD

**Issue by zoider** [Trsak/esx_inventoryhud#37]
So is there support comming for society inventory's like armory's.
Because now the problem is, if you have like 10 bread and you drop in inside the armory of the society with a count of 1000 another player can withdraw 1000 bread from it. 

Would love to see a solution to support the armory and vault of the society also.

Thanks anyway.

**Comment by lvp11** [comment]
+1

Please!

**Comment by Deniel00** [comment]
+1 👍

**Comment by markmorris** [comment]
+1

**Comment by LuffyCosta** [comment]
+1
