### ISSUE TITLE
Property storage issue with other players

### ISSUE THREAD

**Issue by moler14** [Trsak/esx_inventoryhud#39]
When in my property with another player/freind i am able to doposit items to my storage, however when my freind looks into the storage he is able to see the items, i think this is fine, however, he is able to deposit items into the storage box also ( again i think this is fine and should be allowed ) but the items show for him that hes added them, removes them from his inventory, but then i am unable to see them, and when he re-opens the storage, the items he added are now gone.

**Comment by Trsak** [comment]
Actually i though that player who is just invinted into someone's property can't access it's items. Will look into it.

**Comment by moler14** [comment]
Ya np, I like that they can, but obvsly atm its bugged, but whatever you decide with it, well done on the package, much respect and much appreciated 😊

Sent from Mail for Windows 10

**Comment by KingRyuShin** [comment]
This has to do with esx_property.. not inventoryhud
When you invite people into your property instance they have full access to your chest and it always has been like that.

Plus, when you deposite and take something from the chest it doesn't refresh the inventory sometime, you have to close it and reopen it.

**Comment by moler14** [comment]
Ok, but even after we refreshed, the items he put in the storage was gone, il recheck it later to make sure there actually disappearing and not just taking x minutes to update, thanks for the update though.

Sent from Mail for Windows 10
