### ISSUE TITLE
[Suggestion] New command /steal + Fixed-ish Size Inventory

### ISSUE THREAD

**Issue by orloko** [Trsak/esx_inventoryhud#42]
It will get the closest(in front) ped to try steal it(open his/her inventory)
Do animation with timer/bar load, opened inventory.

Can do a lot of RP with it...
example, the 1st clip on this video
https://www.youtube.com/watch?v=RDsIlQapuZM

About the Fixed-ish Size Inventory it's so we can "hide" items on the bottom part,
or just add like a "hide" on the corner of the item when mouse over, the item would be visible again if marked off "unhide item" on the bottom part of the hud, idk. Would be cool

**Comment by moler14** [comment]
opening another playersinventory is already a feature in the latest version, you have to inplement the hud into a command to rob another player, there an example of how to use it with esx_police, make you own method for robbing.
