### ISSUE TITLE
esx_inventoryhud and esx_planting compatibility?

### ISSUE THREAD

**Issue by RagingNaClholic** [Trsak/esx_inventoryhud#43]
https://forum.fivem.net/t/release-esx-inventory-hud-2-3-properties-trunks-players/388318 
Hi!  I'm a lil new to programming and would like to know if theres any compatibility issues with this mod and esx_planting, because for some reason when i'm in the right spot and have the right conditions, i still cant drag an item over use to try and use it. any fixes that you know of? it would be a great help

**Comment by moler14** [comment]
this is not an error with the inventory hud, i use esx_planting and using seed_weed as items works fine, if you have an issue its with something else not inventoryhud
