### ISSUE TITLE
Problem with close

### ISSUE THREAD

**Issue by Er1cx** [Trsak/esx_inventoryhud#45]
Hi, i have problem with this inventory.
When i open that, i have my items, but i cant do anything, i cant drop/use/give and cant close that inventory. Any issue?

**Comment by LowQualityPlays** [comment]
Did you change the name of the resource?
It happened with me when I tried to rename esx_inventoryhud_newupdate, fixed leaving esx_inventoryhud tho.

**Comment by Er1cx** [comment]
Ohhh mate! Thanks a lot! :)
