### ISSUE TITLE
Certain items disapear from property inventory

### ISSUE THREAD

**Issue by markmorris** [Trsak/esx_inventoryhud#47]
So i have the default bread item, but when i drag and drop it disapears from both. However other items work such as black money and weapons

**Comment by KoolAiddTV** [comment]
I'm having this same issue. Also curious how to add it to where you can deposit money into the stash

**Comment by Fluxiitis** [comment]
Same here

**Comment by markmorris** [comment]
Ive noticed another issue with the property inventory which i believe might be the issue. When i drag and drop my dirty money, it gets renamed somehow, that is telling me its looking elsewhere for the item information just on properties. Very strange.

**Comment by wang899** [comment]
You all running kash addon with esx_inventoryhud for properties?

**Comment by Fluxiitis** [comment]
Im running kash multichar. But we fixed it i guess

**Comment by markmorris** [comment]
kash addon?

**Comment by Demo4889** [comment]
> 
> 
> Ive noticed another issue with the property inventory which i believe might be the issue. When i drag and drop my dirty money, it gets renamed to black money, that is telling me its looking elsewhere for the item information just on properties. Very strange.

This is just due to the "local" being named "Black Money". You can easily change that to say "Dirty Money" by modifying the local file that you use, and putting the same name in that of the one in your inventory itself.

**Comment by polarim** [comment]
Any updates on this?

**Comment by EGUltraTM** [comment]
would also love to know the solution we have the same issues with esx_property

**Comment by DaxterPancake** [comment]
Has anyone had any luck fixing this issue?
Been trying to figure it out for awhile now.
