### ISSUE TITLE
Ghost duplicates

### ISSUE THREAD

**Issue by PapaHedge** [Trsak/esx_inventoryhud#49]
We have an issue where cash and dirty money duplicate ghost versions of themselves in the inventory. They cannot be used or dropped. If the original money is removed from the inventory, all of the other images vanish. Any help with this would be massively appreciated.

![image](https://user-images.githubusercontent.com/51750853/59356062-0989b380-8d20-11e9-8e9a-8100cfce9ebf.png)

**Comment by hotatchanh** [comment]
If you have specific money UI then recheck that UI script. If your dev edit es_extended directly for UI ( instead of create a resource to do that ) then you will see this problem. Dont worry this just client side problem and money is not duped

**Comment by PapaHedge** [comment]
I'm sorry, I don't really understand what you've written. I should check es_extended for cash and dirty money ui?

**Comment by cuemur** [comment]
https://image.prntscr.com/image/jvQdevAxQD_lFHZFIxYTFg.png

same.
