### ISSUE TITLE
can not delete exstended

### ISSUE THREAD

**Issue by loibuonbongtoi** [Trsak/esx_inventoryhud#52]
I can't delete extended, if I delete it, everything is broken

**Comment by ericb160** [comment]
i have the same problem :(

**Comment by Demo4889** [comment]
You shouldn't be deleting the entire es_extended. You only have to block out one portion to stop the F2 inventory menu. Make sure you read the instructions again and use Notepad++

**Comment by ericb160** [comment]
i didn't delete the whole thing..  just the code he said to remove
