### ISSUE TITLE
How to use with "Deposit/Withdraw Stock"

### ISSUE THREAD

**Issue by K3IDB** [Trsak/esx_inventoryhud#6]

**Comment by Trsak** [comment]
I am not exactly sure what you mean?

**Comment by K3IDB** [comment]
i mean make inventoryHUD can use with "ESX properties" and "ESX datastore" same inventoryHUD_Truck

**Comment by Trsak** [comment]
This will be added in future.

**Comment by Trsak** [comment]
Just implemented esx_property in latest version. More to come soon.
