### ISSUE TITLE
some people cant see any item 

### ISSUE THREAD

**Issue by ninenite** [Trsak/esx_inventoryhud#63]
![esx invetory](https://user-images.githubusercontent.com/19632855/63212214-15806000-c12b-11e9-89d7-a43c41a25090.png)

this issue on some player and cant see any item 

can u help please ?

thanks

**Comment by Rungrot444** [comment]
![image](https://user-images.githubusercontent.com/30458609/63213411-41551300-c136-11e9-820e-2da4ccaa1766.png)

**Comment by ninenite** [comment]
@Rungrot444  I appreciate :)
