### ISSUE TITLE
Trunk glitch

### ISSUE THREAD

**Issue by Tinky124** [Trsak/esx_inventoryhud#66]
when you disconnect your internet cable, you just drop guns into trunk from inventory, after that, connect it into modem and now you have your glitched guns

Video if you dont understand: 
https://youtu.be/IjHlF6VuPU0?t=23

Another video with lag switch: 
https://youtu.be/kHOfmdVLs1A?t=81

PS. Welcome back bro! :) i hope you can fix this because you are real developer of esx_inventoryhud!

I tried everything to fix this but i cant i dont know, if you can fix this,thanks!!!

**Comment by Trsak** [comment]
Try it with latest [esx_inventoryhud_trunk](https://github.com/Trsak/esx_inventoryhud_trunk) at let me know if problem still happens.

**Comment by Tinky124** [comment]
Ok i will test it and tell you if it is working..

**Comment by Tinky124** [comment]
fixed
