### ISSUE TITLE
Duplicate cash issue

### ISSUE THREAD

**Issue by DarkProvider** [Trsak/esx_inventoryhud#76]
Greetings, 

As of lately, I have implemented the script you've made into my server, everything was working fine except for the cash issue. The cash issue I'm talking about is that when I open my inventory, it will show 2 cash items as in the screenshot provided. If I exclude money and bank all together, I will still be able to see the money icon and can drag it around, however I will not be able to drop nor give the cash to anyone else. What I wanted to know is, if there is any solution for this as it's annoying to stare at the cash you have, knowing that you can't drop nor give it to somebody or look at two cash icons not knowing which is which...

![Screenshot_11](https://user-images.githubusercontent.com/53404124/96942068-62e92180-14d4-11eb-917b-2e80f7e1c757.jpg)

Thanks in advance!

**Comment by XvenDeR** [comment]
You have to configure for your framework yourself, no one gonna do it for you. Many people use different versions.

**Comment by DarkProvider** [comment]
What are you talking about mate? I'm using the ESX (Latest first version V1.3) like everyone and the script is supposed to work with the newest ESX versions. Most people use ESX and even the script is made specifically for the ESX framework as far as I know, right?

**Comment by DarkProvider** [comment]
The cash thing is a glitch which is not supposed to happen based on my research

**Comment by DarkProvider** [comment]
The cash thing is a glitch which is not supposed to happen, based on my research.

**Comment by DarkProvider** [comment]
I honestly don't think that anyone would be happy with having 2 cash items in their inventory, one without an icon and the other with an icon but can't even drop it nor give it to anyone else

**Comment by XvenDeR** [comment]
With a slight adjustments you can fix these, depends what your framework uses as I have mentioned before.

**Comment by DarkProvider** [comment]
I have tried to exclude both money and bank from showing in the config as I mentioned above but that way it will still show the money with the icon and you will be able to drag it and move it around, however you will not be able to give anything from it to someone nor drop anything. You would be basically stuck with that useless item in your inventory. I don't that to happen, I want people to be able to give/drop that money I'm talking about if you get me. The config doesn't allow you to adjust it like that.

**Comment by johnsoul777** [comment]
> He intentado excluir tanto el dinero como el banco para que no se muestren en la configuración como mencioné anteriormente, pero de esa manera aún mostrará el dinero con el ícono y podrá arrastrarlo y moverlo, sin embargo, no podrá dar nada de eso a alguien ni dejar caer nada. Básicamente estarías atrapado con ese artículo inútil en tu inventario. Pero no creo que eso suceda, quiero que la gente pueda dar / soltar ese dinero del que estoy hablando si me entiendes. La configuración no te permite ajustarlo así.

Prueba esto amigo

Config = {}
Config.Locale = "es"
Config.IncludeCash = false -- Include cash in inventory?
Config.IncludeWeapons = true -- Include weapons in inventory?
Config.IncludeAccounts = true -- Include accounts (bank, black money, ...)?
Config.ExcludeAccountsList = {"bank"} -- List of accounts names to exclude from inventory
Config.OpenControl = 289 -- Key for opening inventory. Edit html/js/config.js to change key for closing it.

-- List of item names that will close ui when used
Config.CloseUiItems = {"coca","headbag", "tunerchip", "cigarette", "rarecigar", "fixkit", "fixkit_large", "cloth", "notepad", "lotteryticket", "lockpick", "fishingrod", "crowbar", "transmitter", "binoculars", "headbag", "dice", "bulletproof_vest", "medikit", "bandage", "vicodin", "gauze", "morphine", "cigarett"}

**Comment by DarkProvider** [comment]
Hey man, thanks for trying but sadly I have already tried that but that doesn't really fix my issue. I want people to still be able to use the money inside the inventory like giveing it to people and dropping them in some situations.

**Comment by XvenDeR** [comment]
Go here and change to money
https://github.com/Trsak/esx_inventoryhud/blob/2b22e72c032ddc08f174ab75f51a15fea146272d/client/main.lua#L291

**Comment by DarkProvider** [comment]
The solution of @johnsoul777 worked perfectly actually, although now I'm missing the icon. However, that can be solved!

**Comment by XvenDeR** [comment]
Add an icon named "cash" or "money" also you should decide what helps you and what's not, you are so confusing....

**Comment by DarkProvider** [comment]
Neither do work mate, I'm confused myself

**Comment by DarkProvider** [comment]
What you are telling me to do is to change the money option to cash when I have that "IncludeCash" function disabled as I followed the solution of @johnsoul777 

The follwing is disabled in the config file as I had duplicate of cash:

When I disabled, the duplication is gone but now I'm stuck with a cash Item without an icon

`            if Config.IncludeCash and money ~= nil and money > 0 then
                moneyData = {
                    label = _U("cash"),
                    name = "money",
                    type = "item_money",
                    count = money,
                    usable = false,
                    rare = false,
                    limit = -1,
                    canRemove = true
                }

                table.insert(items, moneyData)
            end`

**Comment by DarkProvider** [comment]
And if I don't disable that and apply what you told me to do, I'll get the duplication problem again, honestly you are confusing not me. I'm even getting more confused when you tell me to change anything.

**Comment by DarkProvider** [comment]
Fixed it, what I have done is I turned off the includeCash option in the config file and then renamed the cash icon from cash.png to money.png

**Comment by XvenDeR** [comment]
That is what we were telling you, close the issue.
